config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top' #root to: でルートの入力でhomes#topアクションを実行させる
  # get 'books/index' => 'books#index'
  # get 'books/show' => 'books#show' #URL books/showにアクセスしたときにshowアクションを実行
  # get 'books/edit' => 'books#edit'
  # get 'homes/top' => 'homes#top'
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title,presence: true
  validates :body,presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
    @book = Book.new
  end
  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice]="Book was successfully created."
      redirect_to "/books/#{@book.id}"
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @book=Book.new
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book =Book.find(params[:id])
  end
  def update
    @book=Book.find(params[:id])

    if @book.update(book_params)
      flash[:notice]="Book was successfully updated."
      redirect_to "/books/#{@book.id}"
    else
      render :show
    end
  end

  def destroy
    book=Book.find(params[:id])
    book.destroy # delete record
    redirect_to '/books'
  end

  private
  def book_params
    params.require(:book).permit(:title,:body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= form_with model:@book do |f| %>
  <div class="box">
      <label class="title-text">Title</label>
      <%= f.text_field :title %>
  </div>
  <div class="box">
    <label class="title-text">Body</label>
    <%= f.text_area :body %>
  </div>
  <div class="action">
    <%= f.submit "Update Book" %>
  </div>

  <div class="redirect">
    <span>
      <%= link_to "Show",book_path(@book.id) %>
    </span>
    &nbsp|&nbsp
    <span>
      <%= link_to "Back","/books" %>
    </span>
  </div>

<% end %>

app/views/books/index.html.erb
<h1>Books</h1>
<table><!--tableを作るタグ-->
  <thead><!--表題だけ作るタグ-->
    <th><!--見出し-->
      Title
    </th>
    <th>Body</th>
  </thead>
  <tbody> <!--データ部分を作るタグ-->
    <% @books.each do |book| %>
    <tr> <!--1行を作るタグ-->
      <td><%= book.title %></td>
      <td><%= book.body %></td>
      <td>
        <%= link_to "Show","/books/#{book.id}" %>
      </td>
      <td>
        <%= link_to "Edit","/books/#{book.id}/edit" %>
      </td>
      <td>
        <%= link_to "Destroy","/books/#{book.id}",method: :delete,"data-confirm" =>"really??" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

<h2>New book</h2>

<!--error画面の作成-->
<% if @book.errors.any? %>
  <div class=error-box>
    <h2 class="error-top"><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li class="error-message"><%= message %></li>
      <% end %>
    </ul>
  </div>

  <%= form_with model: Book.new do |f| %>
    <div class="box">
      <div class="error-title">
        <label class="title-text">Title</label>
      </div>
      <div class="error-title">
        <%= f.text_field :title %>
      </div>
    </div>
    <div class="box">
      <div class="error-title">
        <label class="title-text">Body</label>
      </div>
       <div class="error-title">
        <%= f.text_area :body %>
      </div>
    </div>
    <div class="action">
      <%= f.submit "Create Book" %>
    </div>
  <% end %>

<% else %>

  <%= form_with model: Book.new do |f| %>
    <div class="box">
      <label class="title-text">Title</label>
      <%= f.text_field :title %>
    </div>
    <div class="box">
      <label class="title-text">Body</label>
      <%= f.text_area :body %>
    </div>
    <div class="action">
      <%= f.submit "Create Book" %>
    </div>

  <% end %>
<% end %>

app/views/books/show.html.erb
<div class="flash">
  <%= flash[:notice] %>
</div>

<% if @book.errors.any? %>
  <h1>Editing Book</h1>
  <div class=error-box>
    <h2 class="error-top"><%= @book.errors.count %> errors prohibited this book from being saved:</h2>
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li class="error-message"><%= message %></li>
      <% end %>
    </ul>
  </div>

  <%= form_with model: Book.new do |f| %>
    <div class="box">
      <div class="error-title">
        <label class="title-text">Title</label>
      </div>
      <div class="error-title">
        <%= f.text_field :title %>
      </div>
    </div>
    <div class="box">
      <div class="error-title">
        <label class="title-text">Body</label>
      </div>
       <div class="error-title">
        <%= f.text_area :body %>
      </div>
    </div>
    <div class="action">
      <%= f.submit "Update Book" %>
    </div>


    <div class="redirect-show">
      <span>
      <%= link_to "Show","#{@book.id}/edit" %>
      </span>
      &nbsp|&nbsp
      <span>
        <%= link_to "Back","../books" %>
      </span>
    </div>

  <% end %>
<% else %>

<p><span class="b">Title: </span><%= @book.title %></p>
<p><span class="b">Body: </span><%= @book.body %></p>

<div class="redirect-show">
  <span>
    <%= link_to "Edit","#{@book.id}/edit" %>
  </span>
  &nbsp|&nbsp
  <span>
    <%= link_to "Back","../books" %>
  </span>
</div>

<% end %>

app/views/homes/top.html.erb
<h1>ようこそ
  <span class=b>Bookers
  </span>へ！
</h1>
<p>
  <span class=b>Bookers</span>
  では、さまざまな書籍に関するあなたの意見や
</p>
<p>印象を共有し交換することができます</p>
<p><a href="/books">start</a></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>